serve:
  ip: "127.0.0.1" # 默认的ip地址
  host: ":8888" # 端口号
  static: ["/images"] #静态文件目录

log:
  mode: "development" # development | production
  fileEnable: true # 是否启用输出到文件 false  true

amap:
  key: "e03eca649d19b53cacafa10163394d16"
  weatherApi: "https://restapi.amap.com/v3/weather/weatherInfo"
